pluginPrefix: "&e&lKwadraciarze.pl &8&l» &7"
usePrefix: true

plotItem:
  material: "NOTE_BLOCK"
  name: "&6&lBLOK DZIALKI"
  lore:
    - "&7Ten blok umozliwi ci zajecie chunku"
    - "&7tak, aby nikt obcy nie mogl"
    - "&7zniszczyc ci dzialki"

defaultFlags:
  PLACE_STRANGER: false
  PLACE_MEMBER: true
  BREAK_STRANGER: false
  BREAK_MEMBER: true
  PVP: false
  PVE: true
  ANIMAL_SPAWNING: true
  MOB_SPAWNING: true
  CREEPER_EXPLOSION: true
  ENDERMAN_GRIEFING: true
  REDSTONE: true
  BLOCK_INTERACT_STRANGER: false
  BLOCK_INTERACT_MEMBER: true
  ENTITY_TAME_STRANGER: false
  ENTITY_TAME_MEMBER: true
  ENTITY_LEASH_STRANGER: false
  ENTITY_LEASH_MEMBER: true
  ENTITY_DAMAGE_STRANGER: false
  ENTITY_DAMAGE_MEMBER: true
  ENTITY_INTERACT_STRANGER: false
  ENTITY_INTERACT_MEMBER: true
  VEHICLE_DAMAGE_STRANGER: false
  VEHICLE_DAMAGE_MEMBER: true
  VEHICLE_ENTER_STRANGER: false
  VEHICLE_ENTER_MEMBER: true
  SPLASH_POTION_MEMBER: true
  SPLASH_POTION_STRANGER: false
  FALL_DAMAGE: true
  DROWNING_DAMAGE: true
  EXTERNAL_PISTON_PROTECTION: true

messages:
  notPermitted: "&cNie masz uprawnień, aby to zrobić!"
  enteredPlot: "&aWkroczyłeś na działkę gracza &7{plotOwnerName}"
  leftPlot: "&cOpuściłeś działkę gracza &7{plotOwnerName}"
  addedMemberToPlot: "&aDodałeś gracza &f%{user} &ado działki!"
  removedMemberFromPlot: "&cUsunąłeś gracza &f{memberName} &cz działki"
  plotCreated: "&aPomyślnie utworzono działkę o ID &8(&7{plotID}&8)"
  plotDeleted: "&cPomyślnie usunięto działkę o ID &8(&7{plotID}&8)"
  errorUnspecified: "&cPojawił się bliżej nieprzewidziany błąd. Zgłoś ten fakt administratorowi"
  addSelfToPlot: "&cNie możesz dodać samego siebie do działki!"
  notOwner: "&cNie możesz tego zrobić, bo nie jesteś właścicielem tej działki!"
  nullUser: "&cGracz o nicku &f{userName} &cnie istnieje!"
  nullPlot: "&cDziałka na której stoisz lub której koordynaty wpisałeś nie istnieje!"
  senderNotPlayer: "&cThis command can be performed only by a player!"
  plotAlreadyExists: "&cW tym miejscu istnieje już działka!"
  settedFlag: "&aPomyślnie ustawiono flagę &f{flagName} &ana &f{flagValue}"
  flagValueOnPlot: "&aFlaga &f{flagName} &aprzyjmuje na tej działce wartość &f{flagValue}"
  avaibleFlags: "&aLista dostępnych flag:"
  unknownFlag: "&cNie odnaleziono flagi o nazwie &f{flagName}"
  wrongFlagValue: "&cPodałeś niepoprawną wartość! Wpisz &ftrue &c albo &ffalse"
  cannotAddSelfAsMember: "&cWłaściciel działki nie może być jej członkiem!"
  cannotAddSelfToBlacklist: "&cWłaściciel działki nie może być na jej blackliście!"
  addedToBlacklist: "&aPomyślnie dodano gracza &f{user} &ado blacklisty działki o ID &8(&7{plotID}&8)"
  removedFromBlacklist: "&aPomyślnie usunięto gracza &f{user} &az blacklisty działki o ID &8(&7{plotID}&8)"
  defaultVisitPointDescription: "&aOto punkt wizyt gracza &f{userName}"
  nullVisitPoint: "&cPunkt o nazwie &f{visitPointName} &cnie istnieje!"
  visitPointClosed: "&cTen punkt wizyt jest aktualnie zamknięty!"
  notVisitPointOwner: "&cNie możesz tego zrobić, bo nie jesteś właścicielem punktu!"
  marketPuttedOnAuction: "&aPomyślnie wystawiono działkę o ID &8(&7{plotID}&8) &a na sprzedaż za &e%price%"
  marketCancelledAuction: "&aPomyślnie anulowano sprzedaż działki o ID &8(&7{plotID}&8)"
  marketBoughtPlot: "&aPomyślnie zakupiono działkę o ID &8(&7{plotID}&8)"
  blacklistAddedToPlot: "Sztajni zamień to na coś mądrego"
  blacklistRemovedFromPlot: "Sztajni zamień to na coś mądrego"
  flagSetOnPlot: "Sztajni zamień to na coś mądrego"
  flagSetOnGroup: "Sztajni zamień to na coś mądrego"
  flagValuesInGroupAreDifferent: "Sztajni zamień to na coś mądrego"
  cannotAddOwnerToBlacklist: "Sztajni zamień to na coś mądrego"
  cannotAddOwnerAsMember: "Sztajni zamień to na coś mądrego"
  playerIsAlreadyBlacklisted: "Sztajni zamień to na coś mądrego"
  playerIsAlreadyAMember: "Sztajni zamień to na coś mądrego"
  nullGroup: "Sztajni zamień to na coś mądrego"
  groupCreate: "Sztajni zamień to na coś mądrego"
  groupDelete: "Sztajni zamień to na coś mądrego"
  plotAddedToGroup: "Sztajni zamień to na coś mądrego"
  teleportingToVisitPoint: "Sztajni zamień to na coś mądrego"
  teleportedToVisitPoint: "Sztajni zamień to na coś mądrego"
  teleportCancelled: "Sztajni zamień to na coś mądrego"


