pluginPrefix: "&e&lChunkyPlots"
usePrefix: false

plotItem:
  material: "NOTE_BLOCK"
  name: "&6Blok działki"
  lore:
    - "&aPostaw ten blok na wybranym"
    - "&achunku, aby utworzyć tam"
    - "&adziałkę."

defaultFlags:
  PLACE_STRANGER: false
  PLACE_MEMBER: true
  BREAK_STRANGER: false
  BREAK_MEMBER: true
  PVP: false
  PVE: true
  ANIMAL_SPAWNING: true
  MOB_SPAWNING: true
  CREEPER_EXPLOSION: true
  ENDERMAN_GRIEFING: true
  REDSTONE: true
  BLOCK_INTERACT_STRANGER: false
  BLOCK_INTERACT_MEMBER: true
  ENTITY_TAME_STRANGER: false
  ENTITY_TAME_MEMBER: true
  ENTITY_LEASH_STRANGER: false
  ENTITY_LEASH_MEMBER: true
  ENTITY_DAMAGE_STRANGER: false
  ENTITY_DAMAGE_MEMBER: true
  ENTITY_INTERACT_STRANGER: false
  ENTITY_INTERACT_MEMBER: true
  VEHICLE_DAMAGE_STRANGER: false
  VEHICLE_DAMAGE_MEMBER: true
  VEHICLE_ENTER_STRANGER: false
  VEHICLE_ENTER_MEMBER: true
  SPLASH_POTION_MEMBER: true
  SPLASH_POTION_STRANGER: false
  FALL_DAMAGE: true
  DROWNING_DAMAGE: true
  EXTERNAL_PISTON_PROTECTION: true

messages:
   plotCreated: "» Działka o ID {id} została utworzona w świecie {world}"
   plotDeleted: "» Pomyślnie usunięto działkę o ID {id} ze świata {world}"
   enteredPlot: "» Wkroczyłeś na działkę gracza {plotOwner}"
   leftPlot: "» Opuściłeś działkę gracza {plotOwner}"
   plotAlreadyExists: "» W tym miejscu istnieje już działka"
   nullPlot: "» Działka o ID {id} w świecie {world} nie istnieje"
   addedMemberToPlot: "» Dodałeś gracza {user} do działki o ID {id} w świecie {world}"
   addedMemberToGroup: "» Dodałeś gracza {user} do wszystkich działek w grupie {group}"
   removedMemberFromPlot: "» Usunąłeś gracza {user} z działki o ID {id} w świecie {world}"
   removedMemberFromGroup: "» Usunąłeś gracza {user} ze wszystkich działek w grupie {group}"
   blacklistAddedToPlot: "» Dodałeś gracza {user} do blacklisty na działce o ID {id} w świecie {world}"
   blacklistAddedToGroup: "» Dodałeś gracza {user} do blacklisty wszystkich działek w grupie {group}"
   blacklistRemovedFromPlot: "» Usunąłeś gracza {user} z blacklisty na działce o ID {id} w świecie {world}"
   blacklistRemovedFromGroup: "» Usunąłeś gracza {user} z blacklisty wszystkich działek w grupie {group}"
   flagSetOnPlot: "» Ustawiłeś wartość flagi {flag} na {value} na działce o ID {id} w świecie {world}"
   flagSetOnGroup: "» Ustawiłeś wartość flagi {flag} na {value} na wszystkich działkach w grupie {group}"
   flagValueOnPlot: "» Flaga {flag} przyjmuje wartość {value} na działce o ID {id} w świecie {world}"
   flagValueOnGroup: "» Flaga {flag} przyjmuje wartość {value} na wszystkich działkach z grupy {group}"
   flagValuesInGroupAreDifferent: "» Wartości flag na działkach w wybranej grupie nie są jednakowe"
   unknownFlag: "» Flaga o nazwie {flag} nie istnieje"
   wrongFlagValue: "» Flaga o nazwie {flag} nie przyjmuje wartości {value}"
   notOwner: "» Nie możesz wykonać tej operacji, gdyż nie jesteś właścicielem działki"
   notPermitted: "» Nie masz uprawnień, aby to zrobić"
   cannotAddOwnerToBlacklist: "» Nie możesz dodać właściciela działki do czarnej listy"
   cannotAddOwnerAsMember: "» Nie możesz dodać właściciela działki do niej jako jej członka"
   playerIsAlreadyBlacklisted: "» Gracz {user} znajduje się już na czarnej liście"
   playerIsAlreadyAMember: "» Gracz {user} jest już dodany do tej działki bądź grupy działek"
   nullUser: "» Gracz o nicku {user} nigdy nie był na serwerze"
   nullGroup: "» Grupa o nazwie {group} nie istnieje"
   groupCreate: "» Grupa o nazwie {group} została utworzona"
   groupDelete: "» Grupa o nzawie {group} została usunięta"
   plotAddedToGroup: "» Działka o ID {id} ze świata {world} została dodana do grupy {group}"
   defaultVisitPointDescription: "» Oto punkt odwiedzin pewnego bardzo miłego gracza :)"
   nullVisitPoint: "» Punkt odwiedzin o nazwie {visitPointName} nie istnieje"
   visitPointUnavaible: "» Ten punkt odwiedzin jest obecnie nieczynny"
   notVisitPointOwner: "» Nie możesz tego zrobić, bo nie jesteś właścicielem tego punktu odwiedzin"
   teleportingToVisitPoint: "» Teleportacja do punktu odwiedzin {visitPointName} odbędzie się za 5 sekund..."
   teleportedToVisitPoint: "» Teleportowano do punktu odwiedzin {visitPointName}"
   teleportCancelled: "» Teleportacja została anulowana, gdyż poruszyłeś się"
   teleportInProgress: "» Jesteś już w trakcie teleportacji!"
   senderNotPlayer: "» Aby wykonać tą komendę musisz być graczem!"


